### ISSUE TITLE
releases are missing from English osscons site

### ISSUE THREAD

**Issue by GitMensch** [opensourcecobol/opensource-cobol#32]
https://www.osscons.jp/Open-COBOL-Solution-WG/download/ stops at 1.3.0 - I suggest to remove the Downloads part there and replace it with a link to https://github.com/opensourcecobol/opensource-cobol/releases

**Comment by tina227** [comment]
@GitMensch.
Thank you for pointing out.
Changed to redirect to download page of github, please see.
